Final touch ups to refactored code before merging to main.
canonical/spark-client-snap pull request #19
Opened 2023-01-05 10:45 UTC by averma-canonical

Addressing review comments shared by Rob.

2023-01-05 11:43 UTC, deusebio commented on spark_client/domain.py
> +        return f"{self.environ['SNAP_USER_DATA']}/.scala_history"
maybe we can just have another property snap_user_data

2023-01-05 11:44 UTC, deusebio approved these changes
All good! Just a minor comment

2023-01-06 11:25 UTC, grobbie requested changes
thanks, just one action for resolution please

2023-01-06 11:25 UTC, grobbie commented on spark_client/utils.py
> +def parse_arguments_with(parsers=[], namespace=None):
please provide some code commentary to the methods in this file

2023-01-06 11:54 UTC, grobbie approved these changes
thanks, looks good

2023-01-06 12:05 UTC, merged