Introducing lighkube, draft for discussion.
canonical/spark-client-snap pull request #44
Opened 2023-03-20 12:31 UTC by averma-canonical

Open Issues
- lint problems (mypy)

2023-03-20 16:16 UTC, deusebio commented on spark_client/services.py
> +        kubectl_cmd="kubectl",
**todo** We don't need this anymore, do we?

2023-03-20 16:22 UTC, deusebio reviewed
Very nice! This is exactly what I had in mind, but i was not sure it was really possible to have two implementations: one with kubectl and the other one with lightkube, that one can use interchangeably in the registry!!!

Well done!!!

I just had a quick glance and everything seems to me to go in the right direction, but I just wanted to play a bit around with this.

2023-03-23 21:16 UTC, deusebio requested changes
Code is shaping up well! I really enjoyed how the code had been structured. There a few issues that needs to be addressed before merging though

2023-03-23 21:16 UTC, deusebio commented on spark_client/services.py
> +                f"{os.getenv('SNAP')}/python/spark_client/resources/lightkube_jinja_templates/serviceaccount_yaml.tmpl"
**issue** this won't work outside of snap. Beside, in general we should never access envs using os.getenv. We defined the Defaults object to be able to proxy and centralize the envs that we use, such that we have control on these. If we use os.env scattered around, we then lose this control 

Anyhow, these are resources and as such, there is a pythonic way to access them which is using this library

https://importlib-resources.readthedocs.io/en/latest/using.html

2023-03-23 21:16 UTC, deusebio commented on spark_client/services.py
> +        if resource_type == "serviceaccount":
**suggestion** We could use Enum for handling resource_type, given they are values chosen from a set of values

https://docs.python.org/3/library/enum.html

This should make it more typed, and also avoid to use strings, which are error prone

2023-03-23 22:05 UTC, deusebio commented on spark_client/services.py
> +            primary_account = self.get_primary()
**todo** I believe this does not comply with the signature. The method is supposed to return None if there is no primary. There was a bug in the code, that I have corrected in the PR #45

2023-03-24 09:03 UTC, welpaolo approved these changes
Looks good to me. Please resolve the comments done by Enrico

2023-03-24 09:03 UTC, welpaolo commented on spark_client/cli/service_account_registry.py
>          print(user_id)
logger

2023-03-27 13:48 UTC, grobbie requested changes
Please remove the test kubeconfig file from this PR and generate one in a test setup method instead

2023-03-27 13:48 UTC, grobbie commented on tests/unittest/resources/data/kubeconfig.yaml
> +apiVersion: v1
I don't like this getting committed to git's memory full of test public keys and tokens. Please remove this file from the PR and generate one during test setup instead.

2023-04-03 08:11 UTC, deusebio approved these changes
LGTM

2023-04-03 09:32 UTC, grobbie approved these changes
thanks

2023-04-03 09:34 UTC, merged